#!/bin/bash

set -e

BUILDCURL_URL=${BUILDCURL_URL:=http://buildcurl.com/}

exec curl -sSL $BUILDCURL_URL -X POST \
	-d "target=$(cat /etc/version)" \
	-d "prefix=$PREFIX" \
	-d "recipe=$1" \
	-d "version=$2"
