#!/bin/bash

set -e

BUILDCURL_URL=${BUILDCURL_URL:=http://buildcurl.com/}

cmd="curl $BUILDCURL_URL --get -A 'buildcurl/internal' --connect-timeout 5 -d target=$(cat /etc/version) -d prefix=$PREFIX -d recipe=$1 -d version=$2"

# display build logs
$cmd -s -o /dev/stderr

# fetch binary
exec $cmd -sL --fail -o -
