#!/usr/bin/env bash
# Build Path: /app/.heroku/php/
# Build Deps: php-5.5.12

OUT_PREFIX=$1

# fail hard
set -o pipefail
# fail harder
set -eux

DEFAULT_VERSION="1.2.0"
dep_version=${VERSION:-$DEFAULT_VERSION}

echo "-----> Bundling Composer (${dep_version})..."

buildcurl php | tar xz -C $OUT_PREFIX

export PATH=${OUT_PREFIX}/bin:$PATH

curl -sS https://getcomposer.org/installer | php -- \
  --version=${dep_version} \
  --filename=composer \
  --install-dir=${OUT_PREFIX}/bin

php ${OUT_PREFIX}/bin/composer --version
mv ${OUT_PREFIX}/bin/composer /tmp/composer
rm -rf ${OUT_PREFIX}/*
mkdir -p ${OUT_PREFIX}/bin
mv /tmp/composer ${OUT_PREFIX}/bin/composer

echo "-----> Done."
