#!/bin/bash

OUT_PREFIX=$1

# fail hard
set -o pipefail
# fail harder
set -eu

echo "-> Building libffi ${VERSION}..."

tmpdir=$(mktemp -d)

pushd $tmpdir
curl -s "ftp://sourceware.org/pub/libffi/libffi-${VERSION}.tar.gz" -o - | tar xzf - --strip-components=1
env CFLAGS=-fPIC ./configure --enable-static --disable-shared --prefix=${OUT_PREFIX}
make
make install
# copy ffi headers in a place where ruby can find them
cp -r ${OUT_PREFIX}/lib/libffi-${VERSION}/include ${OUT_PREFIX}/
popd

rm -rf $tmpdir
echo "-> DONE"
