#!/usr/bin/env bash
# Build Path: /app/.heroku/python/
# Build Deps: libraries/sqlite

OUT_PREFIX=$1

set -ex
set -o pipefail

buildcurl sqlite | tar xz -C $OUT_PREFIX

VERSION=${VERSION:=2.7.6}
dep_dirname="Python-$VERSION"

echo "Building $dep_dirname..."
SOURCE_TARBALL="https://python.org/ftp/python/$VERSION/$dep_dirname.tgz"
curl -L $SOURCE_TARBALL | tar xz --strip-components=1

./configure --prefix=$OUT_PREFIX
make -j ${JOBS:=1}
make install
if test -f $OUT_PREFIX/bin/python3 ; then
	ln -s $OUT_PREFIX/bin/python3 $OUT_PREFIX/bin/python
fi
rm -rf $OUT_PREFIX/lib/python*/{__pycache__,test}

echo "-----> Done."
