#!/bin/bash

OUT_PREFIX=$1

set -e
set -o pipefail

DEFAULT_VERSION="2.0.0-p648"
dep_version=${VERSION:-$DEFAULT_VERSION}
if [ "$dep_version" = "2.0.0" ]; then
	dep_version="2.0.0-p648"
elif [ "$dep_version" = "1.9.3" ]; then
	dep_version="1.9.3-p551"
fi
full_name="ruby-$dep_version"
version="${dep_version/-*/}"
name="ruby-$version"
major_ruby="$(echo $version | sed 's/^\([0-9]\+\.[0-9]\+\).*/\1/')"
filename="$name.tgz"

dep_dirname=ruby-${dep_version}
dep_archive_name=${dep_dirname}.tar.gz
dep_protocol=https
if [ "$(cat /etc/version)" == "sles:11" ]; then
	dep_protocol=http
fi
dep_url=${dep_protocol}://cache.ruby-lang.org/pub/ruby/${major_ruby}/${dep_archive_name}

echo "-> Building ruby ${dep_version}..."

buildcurl libyaml 0.1.6 | tar xz -C $OUT_PREFIX
buildcurl libffi 3.2.1 | tar xz -C $OUT_PREFIX
curl -L ${dep_url} | tar xz

pushd ${dep_dirname}
debugflags="-g" ./configure \
    --prefix=${OUT_PREFIX} \
    --disable-install-doc \
    --enable-load-relative
CPATH=$OUT_PREFIX/include:$CPATH \
	CPPATH=$OUT_PREFIX/include:$CPPATH \
	LIBRARY_PATH=$OUT_PREFIX/lib:$LIBRARY_PATH \
	make -s -j ${JOBS:=1}
make install -s
popd

echo "-> DONE"
