#!/usr/bin/env bash
# Build Path: /app/.heroku/python/

OUT_PREFIX=$1

set -o pipefail
set -eux

echo "Building SQLite..."


SOURCE_TARBALL='https://www.sqlite.org/sqlite-autoconf-3070900.tar.gz'

curl $SOURCE_TARBALL | tar xz --strip-components=1
./configure --prefix=$OUT_PREFIX
make -j ${JOBS:=1}
make install
echo "-----> Done."
