#!/bin/bash
# Build Path: /app/.heroku/php/

OUT_PREFIX=$1

# fail hard
set -o pipefail
# fail harder
set -eux

DEFAULT_VERSION="1.2.8"
dep_version=${VERSION:-$DEFAULT_VERSION}
dep_dirname=zlib-${dep_version}
dep_archive_name=${dep_dirname}.tar.gz
# dep_url=http://zlib.net/${dep_archive_name} # often down
dep_url=http://sourceforge.net/projects/libpng/files/zlib/${dep_version}/${dep_archive_name}/download

echo "-----> Building zlib ${dep_version}..."

curl -L ${dep_url} | tar xz

pushd ${dep_dirname}
./configure --prefix=${OUT_PREFIX}
make -s -j 9
make install -s
popd

echo "-----> Done."
