#!/bin/bash

DOCKER_ORG=${DOCKER_ORG:=buildcurl}

push_docker_image() {
	file=$1
	osversiondir=$(dirname $file)
	osfamilydir=$(dirname $osversiondir)
	osversion=$(basename $osversiondir)
	osfamily=$(basename $osfamilydir)
	target="$osfamily:$osversion"
	docker_tag="$DOCKER_ORG/$osfamily:$osversion"

	echo $docker_tag
	docker push $DOCKER_ORG/$osfamily:$osversion
}

push_docker_image "$1"
